In [19]:
import pickle

with open('서울교통공사_지하철혼잡도정보_20211231.csv', 'r') as f:
    raw = f.readlines()

raw_list=[]
for line in raw:
    raw_list.append(line[:-1].split(','))
#print(raw_list)

time_slots=raw_list[0][6:]
#print(time_slots)
date_type_list = list(set([x[1] for x in raw_list[1:]]))
#print(date_type_list)
line_type_list = list(set([x[5] for x in raw_list[1:]]))
#print(line_type_list)

data=[]
for x in raw_list[1:]:
    sub_list=[]
    for index, value in enumerate(x[1:]):
        if index == 3:
            continue
        if index == 0:
            sub_list.append(date_type_list.index(value))
        elif index == 4:
            sub_list.append(line_type_list.index(value))
        elif index > 4:
            sub_list.append(float(value))
        else:
            sub_list.append(int(value))
    data.append(sub_list)
#print(data)

pickle_dict = dict()
pickle_dict['time_slot']=time_slots
pickle_dict['date_type_list']=date_type_list
pickle_dict['line_type_list']=line_type_list
pickle_dict['data']=data
pickle_dict['comment']='comment'

with open('pickle.data', 'wb') as f:
    pickle.dump(pickle_dict, f)

In [27]:
import numpy as np

#print(data)
np_data = np.array(data, dtype=np.float32)
print(np_data.shape)
sub = np_data[::2,4:]
print(sub)

(1704, 41)
[[ 9.1  8.6  9.3 ... 20.3 12.6 10.3]
 [ 7.   6.8 10.2 ... 18.5 11.8  9.1]
 [ 7.8  7.4 10.9 ... 15.1 10.7  7.1]
 ...
 [ 7.   3.   2.2 ...  1.6  2.2  1.5]
 [ 9.3  4.1  2.6 ...  0.9  1.1  0.5]
 [ 0.   0.   0.  ...  0.   0.   0. ]]
