In [8]:
import numpy as np

In [9]:
print(np.version.version)

1.23.1


In [11]:
array1 = np.array([x for x in range(6)])
list1 = [x for x in range(6)]
print(array1)
print(list1)
print(type(array1))

[0 1 2 3 4 5]
[0, 1, 2, 3, 4, 5]


In [22]:
list2 = [1,2,3,'a','b','c']
print(list2)
array2 = np.array(list2)
print(array2)
print(array2.dtype)

array3 = np.array([1,2,3,10.1, 20.2, 30.3])
print(array3)
print(array3.dtype)

[1, 2, 3, 'a', 'b', 'c']
['1' '2' '3' 'a' 'b' 'c']
<U11
[ 1.   2.   3.  10.1 20.2 30.3]
float64


In [20]:
# 30에서 55사이 (55불포함) 홀수로 ndarray 만들기
array4 = np.array([x for x in range(31, 55, 2)], dtype=np.float64)
print(array4)

[31. 33. 35. 37. 39. 41. 43. 45. 47. 49. 51. 53.]


In [31]:
list5 = [x for x in range(10,50,2)]
print(list5)
array5 = np.arange(10., 50., 2.)
print(array5)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48.]


In [33]:
# ndarray, -3.14에서 3.14까지(stop), 스텝 0.5
array5 = np.arange(-3.14, 3.14, 0.5)
print(array5)

[-3.14 -2.64 -2.14 -1.64 -1.14 -0.64 -0.14  0.36  0.86  1.36  1.86  2.36
  2.86]


In [35]:
array6 = np.linspace(10, 100, 5)
print(array6)
array7 = np.linspace(-5, 5, 70)
print(array7)

[ 10.   32.5  55.   77.5 100. ]
[-5.         -4.85507246 -4.71014493 -4.56521739 -4.42028986 -4.27536232
 -4.13043478 -3.98550725 -3.84057971 -3.69565217 -3.55072464 -3.4057971
 -3.26086957 -3.11594203 -2.97101449 -2.82608696 -2.68115942 -2.53623188
 -2.39130435 -2.24637681 -2.10144928 -1.95652174 -1.8115942  -1.66666667
 -1.52173913 -1.37681159 -1.23188406 -1.08695652 -0.94202899 -0.79710145
 -0.65217391 -0.50724638 -0.36231884 -0.2173913  -0.07246377  0.07246377
  0.2173913   0.36231884  0.50724638  0.65217391  0.79710145  0.94202899
  1.08695652  1.23188406  1.37681159  1.52173913  1.66666667  1.8115942
  1.95652174  2.10144928  2.24637681  2.39130435  2.53623188  2.68115942
  2.82608696  2.97101449  3.11594203  3.26086957  3.4057971   3.55072464
  3.69565217  3.84057971  3.98550725  4.13043478  4.27536232  4.42028986
  4.56521739  4.71014493  4.85507246  5.        ]


In [41]:
array8 = np.zeros(10)
print(array8)
array9 = np.zeros(20)
array9[10]=1
print(array9)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [44]:
list10 = [x for x in range(6)]
print(list10)
array10_1  = np.zeros(len(list10))
print(array10_1)
array10_2 = np.zeros_like(list10)
print(array10_2)

[0, 1, 2, 3, 4, 5]
[0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0]


In [49]:
array11 = np.arange(10, 50)
print(array11)
print(array11[::2])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [52]:
print(array11.ndim)
print(array11.shape)

1
(40,)


In [55]:
array12 = np.array([[1,2,3],[10,20,30]])
print(array12)
print(array12.ndim)
print(array12.shape)
array13 = array12.reshape(3,2)
print(array13)
print(array13.ndim)
print(array13.shape)

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
[[ 1  2]
 [ 3 10]
 [20 30]]
2
(3, 2)


In [56]:
# -10 에서 30 사이(포함) 균일하게 분포하는 숫자 20개를, shape (4,5)로 만들기.
array14 = np.linspace(-10, 30, 20).reshape(4,5)
print(array14)

[[-10.          -7.89473684  -5.78947368  -3.68421053  -1.57894737]
 [  0.52631579   2.63157895   4.73684211   6.84210526   8.94736842]
 [ 11.05263158  13.15789474  15.26315789  17.36842105  19.47368421]
 [ 21.57894737  23.68421053  25.78947368  27.89473684  30.        ]]


In [65]:
array15 = np.arange(100,120).reshape(4,5)
print(array15)
print(array15[0:2,2:4])
print(array15[2:,:3])

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]
[[102 103]
 [107 108]]
[[110 111 112]
 [115 116 117]]


In [69]:
x = (array15%2==0)
print(x)
print(array15[x])
print(array15[array15%2==0])

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]
[100 102 104 106 108 110 112 114 116 118]
[100 102 104 106 108 110 112 114 116 118]


In [75]:
array16 = np.array([1,2,3,4,5])
#x = array16[1:3]
x = array16[1:3].copy()
print(x)
x[0]=10
print(x)
print(array16)
## array17 = array16.append(10)

[2 3]
[10  3]
[1 2 3 4 5]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [87]:
a1 = np.arange(10, 15)
a2 = np.arange(20, 25)
a2_2 = np.arange(30,35)
print(a1)
print(a2)
a3 = np.vstack((a1,a2,a2_2))
print(a3)
a4 = np.hstack((a2,a1))
print(a4)
a2[0]=100
print(a2)
print(a4)

[10 11 12 13 14]
[20 21 22 23 24]
[[10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]
[20 21 22 23 24 10 11 12 13 14]
[100  21  22  23  24]
[20 21 22 23 24 10 11 12 13 14]


In [91]:
a1 = np.arange(10,19).reshape(3,3)
a2 = np.arange(20,29).reshape(3,3)
print(a1)
print('.........')
print(a2)
a3 = np.vstack((a1,a2))
print(a3)
a4 = np.hstack((a2,a1))
print(a4)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
.........
[[20 21 22]
 [23 24 25]
 [26 27 28]]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [20 21 22]
 [23 24 25]
 [26 27 28]]
[[20 21 22 10 11 12]
 [23 24 25 13 14 15]
 [26 27 28 16 17 18]]


In [94]:
a1 = np.arange(10, 15)
a2 = np.arange(20, 25)
a2_2 = np.arange(30,35)
print(a1)
print(a2)

list1 = [1,2,3,4,5]
list2 = [10,20,30,40,50]
print(list1 + list2)
s1 = 'abc'
s2 = 'def'
print(s1+s2)
print(a1+a2)

[10 11 12 13 14]
[20 21 22 23 24]
[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
abcdef
[30 32 34 36 38]


In [95]:
a1 = np.arange(10,50).reshape(4,10)
print(a1)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [103]:
print(np.vsplit(a1,2))

[array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])]


In [102]:
x = np.hsplit(a1,2)
print(x)
#print(type(x))

[array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]]), array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])]


In [108]:
# axis
def pinfo(x):
    print(x)
    print(x.shape)
    
a1 = np.arange(1,6)
pinfo(a1)

a2 = a1[np.newaxis, :]
pinfo(a2)

a3 = a1[:, np.newaxis]
pinfo(a3)

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]
(1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [113]:
a1 = np.arange(10)
print(a1, a1.sum())
a2 = np.arange(20).reshape(2,10)
print(a2.shape)
print(a2, a2.sum(axis=0))
print(a2, a2.sum(axis=1))

[0 1 2 3 4 5 6 7 8 9] 45
(2, 10)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] [10 12 14 16 18 20 22 24 26 28]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] [ 45 145]
