In [12]:
import pickle
import requests
from lxml import etree
import time

base_url = 'https://movie.naver.com/movie/bi/mi/basic.naver?code='

with open('NaverMovie1.pickle', 'rb') as f:
    movie_info = pickle.load(f)

for m in movie_info:
    response = requests.get(base_url+m[0])
    time.sleep(2)
    page = etree.HTML(response.content)
    x = page.xpath('//dl[@class="info_spec"]//a[contains(@href,"?open")]')
    if(len(x)==2):
        t = x[1].text.split('.')
        m.append(x[0].text)  # year
        m.append(t[-2])   # month
        m.append(t[-1])   # day
        print(m)

['81888', '탑건: 매버릭', ' 2022', '06', '22']
['191613', '클라우스', ' 2019', '11', '15']
['144584', '할머니의 먼 집', ' 2016', '09', '29']
['171539', '그린 북', ' 2019', '01', '09']
['174830', '가버나움', ' 2019', '01', '24']
['186114', '밥정', ' 2020', '10', '07']
['144906', '베일리 어게인', ' 2018', '11', '22']
['169240', '아일라', ' 2018', '06', '21']
['192613', '디지몬 어드벤처 라스트 에볼루션 : 인연', ' 2021', '02', '17']
['196843', '극장판 바이올렛 에버가든', ' 2020', '11', '12']
['157243', '당갈', ' 2018', '04', '25']
['217719', '명탐정 코난: 할로윈의 신부', ' 2022', '07', '13']
['181710', '포드 V 페라리', ' 2019', '12', '04']
['179518', '주전장', ' 2019', '07', '25']
['154667', '덕구', ' 2018', '04', '05']
['35939', '클래식', ' 2003', '01', '30']
['196828', '그대, 고맙소 : 김호중 생애 첫 팬미팅 무비', ' 2020', '09', '29']
['18988', '라이언 일병 구하기', ' 1998', '09', '12']
['213746', '장민호 드라마 최종회', ' 2022', '01', '24']
['10016', '나 홀로 집에', ' 1991', '07', '06']
['69105', '월-E', ' 2008', '08', '06']
['156464', '보헤미안 랩소디', ' 2018', '10', '31']
['29217', '글래디에이터', ' 2000', '06', '03']
[

['172780', '스파이 지니어스', ' 2020', '01', '22']
['190244', '러브 앳', ' 2019', '11', '27']
['143469', '어메이징 메리', ' 2017', '10', '04']
['11003', '천장지구', ' 1990', '10', '13']
['172174', '어느 가족', ' 2018', '07', '26']
['154379', '내 어깨 위 고양이, 밥', ' 2017', '01', '04']
['51143', '과속스캔들', ' 2008', '12', '03']
['10561', '대부 3', ' 1991', '03', '16']
['32610', '공공의 적', ' 2002', '01', '25']
['138877', '불량소녀, 너를 응원해!', ' 2016', '09', '21']
['19469', '네고시에이터', ' 1998', '10', '24']
['11002', '혹성탈출', ' 1969', '09', '25']
['187322', '크루엘라', ' 2021', '05', '26']
['10688', '뻐꾸기 둥지 위로 날아간 새', ' 1977', '09', '17']
['160135', '서서평, 천천히 평온하게', ' 2017', '04', '26']
['75378', '파수꾼', ' 2011', '03', '03']
['203715', '너에게 가는 길', ' 2021', '11', '17']
['92075', '어바웃 타임', ' 2013', '12', '05']
['169349', '뽀로로 극장판 공룡섬 대모험', ' 2017', '12', '07']
['13234', '파 앤드 어웨이', ' 1992', '08', '01']
['130849', '모아나', ' 2017', '01', '12']
['34093', '오아시스', ' 2002', '08', '15']
['18934', '마틸다', ' 1997', '08', '09']
['39857', '코치 카터', ' 200

In [14]:
cut = []
for m in movie_info:
    if len(m) != 5:
        print(m)
        cut.append(m)

['151196', '원더']
['175092', '먼 훗날 우리']
['17421', '쇼생크 탈출']
['10200', '터미네이터 2:오리지널']
['10102', '사운드 오브 뮤직']
['10002', '빽 투 더 퓨쳐']
['17159', '포레스트 검프']
['18847', '타이타닉']
['106360', '위대한 쇼맨']
['22126', '인생은 아름다워']
['24452', '매트릭스']
['32686', '센과 치히로의 행방불명']
['14450', '쉰들러 리스트']
['31796', '반지의 제왕: 왕의 귀환']
['34324', '집으로...']
['10048', '죽은 시인의 사회']
['17170', '레옹']
['163788', '알라딘']
['203288', '잭 스나이더의 저스티스 리그']
['30688', '해리 포터와 마법사의 돌']
['19079', '굿 윌 헌팅']
['73372', '세 얼간이']
['19099', '트루먼 쇼']
['31795', '반지의 제왕: 두 개의 탑']
['39636', '지금, 만나러 갑니다']
['62586', '다크 나이트']
['10114', '아마데우스']
['218877', 'RRR: 라이즈 로어 리볼트']
['31013', '빌리 엘리어트']
['35187', '피아니스트']
['10001', '시네마 천국']
['70457', '드래곤 길들이기']
['25915', '아이언 자이언트']
['17153', '토이 스토리']
['10249', '모던 타임즈']
['10244', '늑대와 춤을']
['39584', '코러스']
['14448', '패왕별희 디 오리지널']
['13500', '쥬라기 공원']
['10746', '폴리스 스토리']
['18817', '8월의 크리스마스']
['31726', '엽기적인 그녀']
['31794', '반지의 제왕: 반지 원정대']
['32112', '몬스터 주식회사 3D']
['11608', '메리 포핀스']
['76309', '플립']
['

In [17]:
import numpy as np
mlist = []
for m in movie_info:
    if len(m)==5:
        t = []
        for n in m[2:]:   # skip movie_code, movie_title
            t.append(int(n))
        mlist.append(t)

np_movies = np.array(mlist)
print(np_movies)

[[2022    6   22]
 [2019   11   15]
 [2016    9   29]
 ...
 [1986    7   19]
 [2004    2   20]
 [2005    2   25]]


In [19]:
years_only = np_movies[:, 0]
a = years_only.min()
b = years_only.max()
print(a, b)
xs = np.arange(a, b+1)
ys = np.bincount(years_only-a)

1954 2022


In [20]:
import matplotlib.pyplot as plt

_, axe = plt.subplots()
axe.bar(xs, ys)

<BarContainer object of 69 artists>